catalog:
  default:
    type: sql
    uri: sqlite:////tmp/pyiceberg_catalog.db
    s3.endpoint: http://localhost:9001
    s3.access-key-id: minio
    s3.secret-access-key: minio123
    s3.region: us-east-1
