Engine:
  Local:
    Settings:
      default_temporary_table_engine: StripeLog
      max_execution_time: 600
      allow_experimental_json_type: 1
      send_logs_level: warning

Batcher:
  MaxBatchSize: 1

TipTracker:
  PollInterval: 3600s

Init:
  Setup:
    - create_candidates_table.sql

TipTracker:
  StopAfter: 1

Steps:
  - Stage:
      Files:
        - create_merge_file.sql
    Workers: 1
